storage:
  mode: local
  s3:
    bucket: <BUCKET_NAME>
    accessKey: <ACCESS_KEY>
    secretKey: <SECRET_KEY>

seaweedfs:
  remote:
    enabled: true
    name: cloudstorage
    provider: s3
    bucket: <BUCKET_NAME>
    s3:
      endpoint: s3.<REGION>.amazonaws.com
      region: <REGION> # e.g. us-east-2
      forcePathStyle: false
    mount:
      mountExisting: true

pipelines:
  images:
    mysql:
      tag: "8.4"
