storage:
  mode: local
  azure:
    accountName: <ACCOUNT_NAME>
    accountKey: <ACCOUNT_KEY>
    containerName: <CONTAINER_NAME>

seaweedfs:
  remote:
    enabled: true
    name: cloudstorage
    provider: azure
    bucket: <CONTAINER_NAME>
    mount:
      mountExisting: true

pipelines:
  images:
    mysql:
      tag: "8.4"
