# Use this Values file for installing MLRun CE resources such as: deployments, non cluster resources (.e.g. crd, cluter role) and installing service as clusterIP.
# remember to use a different namespace that used for the cluster resource installation. (support MLRun. mpi, nuclio and kfp pipeline installation)

# We use global values scope to multiplex the docker-registry details to both mlrun and nuclio
global:
  nuclio:
    dashboard:
      nodePort: ""

nuclio:
  crd:
    create: false

mlrun:
  api:
    service:
      type: ClusterIP
      nodePort: ""
  ui:
    service:
      type: ClusterIP
      nodePort: ""

jupyterNotebook:
  service:
    type: ClusterIP
    nodePort: ""
    port: 8888

mpi-operator:
  fullnameOverride: mpi-operator
  crd:
    create: false
  rbac:
    clusterResources:
      create: false

seaweedfs:
  enabled: true
  s3Service:
    type: ClusterIP
    port: 8333
    nodePort: ""

timescaledb:
  service:
    type: ClusterIP
    nodePort: ""

spark-operator:
  enabled: true
  fullnameOverride: spark-operator
  controller:
    replicas: 1
    rbac:
      create: false
    serviceAccount:
      create: true
    leaderElection:
      enable: true
  webhook:
    enable: false
  spark:
    jobNamespaces:
      - mlrun
    serviceAccount:
      create: true
      name: sparkapp
    rbac:
      create: true

spark:
  enabled: true

pipelines:
  service:
    type: ClusterIP
    nodePort: ""
  crd:
    enabled: false
  priority_class:
    enabled: false

strimzi-kafka-operator:
  enabled: false
  
kafka:
  rbac:
    operatorNamespace: controller
  egress:
    enabled: true

kube-prometheus-stack:
  enabled: false
