dependencies:
  - name: nuclio
    version: "0.21.9"
    repository: "https://nuclio.github.io/nuclio/charts"
  - name: mlrun
    version: "0.11.18"
    repository: "https://v3io.github.io/helm-charts/stable"
    condition: mlrun.enabled
  - name: mpi-operator
    version: "0.6.0"
    repository: "https://v3io.github.io/helm-charts/stable"
  - name: seaweedfs
    repository: "https://seaweedfs.github.io/seaweedfs/helm"
    version: "4.0.407"
    condition: seaweedfs.enabled
  - name: spark-operator
    repository: "https://kubeflow.github.io/spark-operator"
    version: "2.1.0"
    condition: spark-operator.enabled
  - name: kube-prometheus-stack
    repository: "https://prometheus-community.github.io/helm-charts"
    version: "72.1.1"
    condition: kube-prometheus-stack.enabled
  - name: strimzi-kafka-operator
    repository: "https://strimzi.io/charts/"
    version: "0.48.0"
    condition: strimzi-kafka-operator.enabled
