{{- if .Values.pipelines.enabled -}}
apiVersion: v1
data:
  metricsConfig: |
    enabled: false
    path: /metrics
    port: 9090
    ignoreErrors: false
  artifactRepository: |
    archiveLogs: {{ .Values.pipelines.archiveLogs }}
    s3:
      endpoint: "{{ include "mlrun-ce.s3.service.host" . }}:{{ include "mlrun-ce.s3.service.port" . }}"
      bucket: "{{ include "mlrun-ce.seaweedfs.s3.bucket" . }}"
      insecure: true
      accessKeySecret:
        name: mlpipeline-seaweedfs-artifact
        key: accesskey
      secretKeySecret:
        name: mlpipeline-seaweedfs-artifact
        key: secretkey
  executor: |
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 0.01
        memory: 32Mi
      limits:
        cpu: 0.5
        memory: 512Mi
kind: ConfigMap
metadata:
  labels:
    application-crd-id: kubeflow-pipelines
  name: workflow-controller-configmap
{{- end -}}
