{{- if and .Values.pipelines.enabled  .Values.pipelines.ui.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
  labels:
    application-crd-id: kubeflow-pipelines
  name: ml-pipeline-ui
{{- end -}}
