{{- if .Values.pipelines.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
  labels:
    application-crd-id: kubeflow-pipelines
  name: ml-pipeline-viewer-crd-service-account
{{- end -}}
