{{- if .Values.timescaledb.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlrun-ce.timescaledb.fullname" . }}-secret
  labels:
    {{- include "mlrun-ce.timescaledb.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.timescaledb.auth.username | quote }}
  password: {{ .Values.timescaledb.auth.password | quote }}
{{- end }}
