apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  annotations:
  generation: 1
  labels:
    application-crd-id: kubeflow-pipelines
  name: workflow-controller
preemptionPolicy: PreemptLowerPriority
value: 1000000

