{{- if .Values.pipelines.priority_class.enabled -}}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  labels:
    application-crd-id: kubeflow-pipelines
  name: workflow-controller
preemptionPolicy: PreemptLowerPriority
value: 1000000
{{- end}}
