{{- if .Values.pipelines.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mlpipeline-seaweedfs-artifact
  labels:
    application-crd-id: kubeflow-pipelines
    {{- include "mlrun-ce.pipelines.labels" . | nindent 4 }}
type: Opaque
stringData:
  accesskey: {{ include "mlrun-ce.seaweedfs.s3.accessKey" . | quote }}
  secretkey: {{ include "mlrun-ce.seaweedfs.s3.secretKey" . | quote }}
{{- end }}
