{{- if .Values.pipelines.enabled -}}
apiVersion: v1
data:
  accesskey: {{ include "mlrun-ce.s3.accessKey" . | b64enc | quote }}
  secretkey: {{ include "mlrun-ce.s3.secretKey" . | b64enc | quote }}
kind: Secret
metadata:
  annotations:
  labels:
    application-crd-id: kubeflow-pipelines
  name: mlpipeline-seaweedfs-artifact
type: Opaque
{{- end -}}
