{{- if .Values.pipelines.enabled -}}
apiVersion: v1
data:
  password: ""
  username: {{ .Values.pipelines.db.username | b64enc | quote }}
kind: Secret
metadata:
  annotations:
  labels:
    application-crd-id: kubeflow-pipelines
  name: mysql-secret
type: Opaque
{{- end -}}
