{{- if .Values.pipelines.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: ml-pipeline-viewer-crd
    application-crd-id: kubeflow-pipelines
  name: ml-pipeline-viewer-crd
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ml-pipeline-viewer-crd
      application-crd-id: kubeflow-pipelines
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      creationTimestamp: null
      labels:
        app: ml-pipeline-viewer-crd
        application-crd-id: kubeflow-pipelines
    spec:
      containers:
      - env:
        - name: MAX_NUM_VIEWERS
          value: "50"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: {{ .Values.pipelines.images.viewerCrdController.repository }}:{{ .Values.pipelines.images.viewerCrdController.tag }}
        imagePullPolicy: Always
        name: ml-pipeline-viewer-crd
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: ml-pipeline-viewer-crd-service-account
      serviceAccountName: ml-pipeline-viewer-crd-service-account
      terminationGracePeriodSeconds: 30
{{- end -}}
