{{- if .Values.pipelines.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ml-pipeline
    application-crd-id: kubeflow-pipelines
  name: ml-pipeline
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ml-pipeline
      application-crd-id: kubeflow-pipelines
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      creationTimestamp: null
      labels:
        app: ml-pipeline
        application-crd-id: kubeflow-pipelines
    spec:
      containers:
        - env:
            # Logging configuration
            - name: PUBLISH_LOGS
              value: "true"
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: pipeline-install-config
                  key: LOG_LEVEL
            - name: PIPELINE_LOG_LEVEL
              value: "1"

            # Pipeline configuration
            - name: AUTO_UPDATE_PIPELINE_DEFAULT_VERSION
              valueFrom:
                configMapKeyRef:
                  key: autoUpdatePipelineDefaultVersion
                  name: pipeline-install-config
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace

            # Object store configuration (SeaweedFS S3 gateway)
            - name: OBJECTSTORECONFIG_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: mlpipeline-seaweedfs-artifact
                  key: accesskey
            - name: OBJECTSTORECONFIG_SECRETACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: mlpipeline-seaweedfs-artifact
                  key: secretkey
            - name: OBJECTSTORECONFIG_HOST
              valueFrom:
                configMapKeyRef:
                  name: pipeline-install-config
                  key: objectStoreServiceHost
            - name: OBJECTSTORECONFIG_PORT
              valueFrom:
                configMapKeyRef:
                  name: pipeline-install-config
                  key: objectStoreServicePort
            - name: OBJECTSTORECONFIG_SECURE
              value: {{ include "mlrun-ce.pipelines.s3.secure" . | quote }}
            - name: OBJECTSTORECONFIG_BUCKETNAME
              valueFrom:
                configMapKeyRef:
                  name: pipeline-install-config
                  key: bucketName
            # Database configuration
            - name: DBCONFIG_CONMAXLIFETIME
              valueFrom:
                configMapKeyRef:
                  name: pipeline-install-config
                  key: ConMaxLifeTime
            - name: DB_DRIVER_NAME
              value: mysql
            - name: DBCONFIG_MYSQLCONFIG_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: DBCONFIG_MYSQLCONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: DBCONFIG_MYSQLCONFIG_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: pipeline-install-config
                  key: pipelineDb
            - name: DBCONFIG_MYSQLCONFIG_HOST
              valueFrom:
                configMapKeyRef:
                  name: pipeline-install-config
                  key: mysqlHost
            - name: DBCONFIG_MYSQLCONFIG_PORT
              valueFrom:
                configMapKeyRef:
                  name: pipeline-install-config
                  key: mysqlPort

            # Driver and launcher images for V2 pipelines
            - name: V2_DRIVER_IMAGE
              value: "{{ .Values.pipelines.images.driver.repository }}:{{ .Values.pipelines.images.driver.tag }}"
            - name: V2_LAUNCHER_IMAGE
              value: "{{ .Values.pipelines.images.launcher.repository }}:{{ .Values.pipelines.images.launcher.tag }}"

          image: {{ .Values.pipelines.images.apiServer.repository }}:{{ .Values.pipelines.images.apiServer.tag }}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - wget
                - -q
                - -S
                - -O
                - '-'
                - http://localhost:8888/apis/v1beta1/healthz
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 2
          name: ml-pipeline-api-server
          ports:
            - containerPort: 8888
              name: http
              protocol: TCP
            - containerPort: 8887
              name: grpc
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - wget
                - -q
                - -S
                - -O
                - '-'
                - http://localhost:8888/apis/v1beta1/healthz
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 2
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      {{- if .Values.seaweedfs.enabled }}
      # Add an init container to wait for the SeaweedFS S3 gateway to be ready before starting the ml-pipeline-api-server
      # Use /status endpoint to check if the S3 gateway is ready, as it returns 200 OK when ready.
      # Same as the Liveness and Readiness probes used in the SeaweedFS S3 deployment.
      initContainers:
        - name: wait-for-seaweedfs
          image: {{ .Values.pipelines.images.apiServer.busybox.repository }}:{{ .Values.pipelines.images.apiServer.busybox.tag }}
          command:
            - sh
            - -c
            - |
              until wget -q -S -O /dev/null http://${SEAWEEDFS_HOST}:${SEAWEEDFS_PORT}/status 2>&1 | grep -q "HTTP/"; do
                echo "Waiting for SeaweedFS S3 to be ready..."
                sleep 5
              done
              echo "SeaweedFS S3 is ready."
          env:
            - name: SEAWEEDFS_HOST
              valueFrom:
                configMapKeyRef:
                  name: pipeline-install-config
                  key: objectStoreServiceHost
            - name: SEAWEEDFS_PORT
              valueFrom:
                configMapKeyRef:
                  name: pipeline-install-config
                  key: objectStoreServicePort
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: ml-pipeline
      serviceAccountName: ml-pipeline
      terminationGracePeriodSeconds: 30
      {{- with .Values.pipelines.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pipelines.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
