{{ if .Values.MinioEnabled.enabled}}
apiVersion: v1
kind: Secret
metadata:
  name: minio-env-secret
data:
  S3_ENDPOINT_URL: {{ include "mlrun-ce.minio.service.url" . }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.minio.rootPassword }}
  AWS_ACCESS_KEY_ID: {{ .Values.minio.rootUser }}
{{- end}}
