{{- if index .Values "kube-prometheus-stack" "enabled" -}}
apiVersion: v1
data:
  model-monitoring-performance.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "datasource",
              "uid": "grafana"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "target": {
              "limit": 100,
              "matchAny": false,
              "tags": [],
              "type": "dashboard"
            },
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": 31,
      "links": [
        {
          "asDropdown": true,
          "icon": "dashboard",
          "includeVars": true,
          "keepTime": true,
          "tags": [],
          "title": "Model Monitoring - Overview",
          "type": "link",
          "url": "d/g0M4uh0Mz/model-monitoring-overview"
        },
        {
          "asDropdown": false,
          "icon": "dashboard",
          "includeVars": true,
          "keepTime": true,
          "tags": [],
          "targetBlank": false,
          "title": "Model Monitoring - Details",
          "tooltip": "",
          "type": "link",
          "url": "d/AohIXhAMk/model-monitoring-details"
        }
      ],
      "liveNow": false,
      "panels": [
        {
          "datasource": {
            "type": "prometheus",
            "uid": "prometheus"
          },
          "description": "Drift metrics that were calculated by the model monitoring offline batch job. The results are based on the average metric value of each feature.  For more details about the calculated metrics please click on the following links:\n",
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisCenteredZero": false,
                "axisColorMode": "text",
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "drawStyle": "line",
                "fillOpacity": 0,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "viz": false
                },
                "lineInterpolation": "linear",
                "lineStyle": {
                  "fill": "solid"
                },
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "auto",
                "spanNulls": true,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": [
              {
                "matcher": {
                  "id": "byName",
                  "options": "hellinger_mean"
                },
                "properties": [
                  {
                    "id": "custom.showPoints",
                    "value": "never"
                  },
                  {
                    "id": "displayName",
                    "value": "Hellinger (mean)"
                  },
                  {
                    "id": "custom.showPoints",
                    "value": "never"
                  }
                ]
              },
              {
                "matcher": {
                  "id": "byName",
                  "options": "kld_mean"
                },
                "properties": [
                  {
                    "id": "custom.showPoints",
                    "value": "never"
                  },
                  {
                    "id": "displayName",
                    "value": "KLD (mean)"
                  }
                ]
              },
              {
                "matcher": {
                  "id": "byName",
                  "options": "tvd_mean"
                },
                "properties": [
                  {
                    "id": "custom.showPoints",
                    "value": "never"
                  },
                  {
                    "id": "displayName",
                    "value": "TVD (mean)"
                  }
                ]
              }
            ]
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 0
          },
          "id": 26,
          "links": [
            {
              "targetBlank": true,
              "title": "Total Variance Distance (TVD)",
              "url": "https://en.wikipedia.org/wiki/Total_variation_distance_of_probability_measures"
            },
            {
              "targetBlank": true,
              "title": "Kullback–Leibler Divergence (KLD)",
              "url": "https://en.wikipedia.org/wiki/Kullback%E2%80%93Leibler_divergence"
            },
            {
              "targetBlank": true,
              "title": "Hellinger",
              "url": "https://en.wikipedia.org/wiki/Hellinger_distance"
            }
          ],
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "table",
              "placement": "right",
              "showLegend": true
            },
            "tooltip": {
              "mode": "multi",
              "sort": "desc"
            }
          },
          "targets": [
            {
              "datasource": {
                "type": "prometheus",
                "uid": "prometheus"
              },
              "editorMode": "code",
              "expr": "drift_metrics{project=\"$PROJECT\", endpoint_id=\"$MODELENDPOINT\"}",
              "legendFormat": "{{` {{ metric }} `}}",
              "range": true,
              "refId": "A"
            }
          ],
          "title": "Drift Measures",
          "type": "timeseries"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "prometheus"
          },
          "description": "Average latency time of processing an event in the selected model endpoint (1-hour rolling average) by time",
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisCenteredZero": false,
                "axisColorMode": "text",
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "drawStyle": "line",
                "fillOpacity": 0,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "viz": false
                },
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "auto",
                "spanNulls": false,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              },
              "unit": "µs"
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 0
          },
          "id": 36,
          "options": {
            "legend": {
              "calcs": [
                "mean"
              ],
              "displayMode": "table",
              "placement": "right",
              "showLegend": true
            },
            "tooltip": {
              "mode": "single",
              "sort": "none"
            }
          },
          "targets": [
            {
              "datasource": {
                "type": "prometheus",
                "uid": "prometheus"
              },
              "editorMode": "code",
              "expr": "avg_over_time(model_latency_seconds_sum{project=\"$PROJECT\", endpoint_id=\"$MODELENDPOINT\"}[1h]) / avg_over_time(predictions_total{project=\"$PROJECT\", endpoint_id=\"$MODELENDPOINT\"}[1h])",
              "legendFormat": "Average Latency",
              "range": true,
              "refId": "A"
            }
          ],
          "title": "Average Latency (1 hour)",
          "type": "timeseries"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "prometheus"
          },
          "description": "Average amount of predictions per second in the selected model endpoint (5-minute rolling average) by time. ",
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisCenteredZero": false,
                "axisColorMode": "text",
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "drawStyle": "line",
                "fillOpacity": 0,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "viz": false
                },
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "auto",
                "spanNulls": true,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "displayName": "Predictions / s",
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 8
          },
          "id": 32,
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "list",
              "placement": "right",
              "showLegend": true
            },
            "tooltip": {
              "mode": "single",
              "sort": "none"
            }
          },
          "targets": [
            {
              "datasource": {
                "type": "prometheus",
                "uid": "prometheus"
              },
              "editorMode": "code",
              "expr": "rate(predictions_total{endpoint_id=\"$MODELENDPOINT\", project=\"$PROJECT\"}[5m])",
              "hide": false,
              "legendFormat": "__auto",
              "range": true,
              "refId": "B"
            }
          ],
          "title": "Predictions (5 Minute Average)",
          "type": "timeseries"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "prometheus"
          },
          "description": "Amount of predictions by time. The prediction counter is based on Prometheus Increase function across the range vector. The result is extrapolated through the time range (5m/1h) which can lead to a non-integer result. For more info about Prometheus Increase method:",
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisCenteredZero": false,
                "axisColorMode": "text",
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "drawStyle": "line",
                "fillOpacity": 0,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "viz": false
                },
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "never",
                "spanNulls": false,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "decimals": 2,
              "mappings": [],
              "noValue": "0",
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              },
              "unit": "none"
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 8
          },
          "hideTimeOverride": false,
          "id": 30,
          "links": [
            {
              "title": "Promethues Increase",
              "url": "https://prometheus.io/docs/prometheus/latest/querying/functions/#increase"
            }
          ],
          "options": {
            "legend": {
              "calcs": [
                "lastNotNull"
              ],
              "displayMode": "table",
              "placement": "right",
              "showLegend": true
            },
            "tooltip": {
              "mode": "multi",
              "sort": "none"
            }
          },
          "targets": [
            {
              "datasource": {
                "type": "prometheus",
                "uid": "prometheus"
              },
              "editorMode": "code",
              "expr": "increase(predictions_total{endpoint_id=\"$MODELENDPOINT\", project=\"$PROJECT\"}[1h])",
              "legendFormat": "Predictions 1 Hour",
              "range": true,
              "refId": "A"
            },
            {
              "datasource": {
                "type": "prometheus",
                "uid": "prometheus"
              },
              "editorMode": "code",
              "expr": "increase(predictions_total{endpoint_id=\"$MODELENDPOINT\", project=\"$PROJECT\"}[5m])",
              "hide": false,
              "legendFormat": "Predictions 5 Minute",
              "range": true,
              "refId": "B"
            }
          ],
          "title": "Predictions Count",
          "type": "timeseries"
        }
      ],
      "refresh": false,
      "schemaVersion": 37,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": [
          {
            "current": {},
            "datasource": "iguazio",
            "definition": "SELECT DISTINCT project FROM model_endpoints",
            "hide": 0,
            "includeAll": false,
            "label": "Project",
            "multi": false,
            "name": "PROJECT",
            "options": [],
            "query": "SELECT DISTINCT project FROM model_endpoints",
            "refresh": 1,
            "regex": "",
            "skipUrlSync": false,
            "sort": 0,
            "tagValuesQuery": "",
            "tagsQuery": "",
            "type": "query",
            "useTags": false
          },
          {
            "current": {},
            "datasource": "iguazio",
            "definition": "SELECT uid FROM model_endpoints where project='$PROJECT';",
            "hide": 0,
            "includeAll": false,
            "label": "Model Endpoint",
            "multi": false,
            "name": "MODELENDPOINT",
            "options": [],
            "query": "SELECT uid FROM model_endpoints where project='$PROJECT';",
            "refresh": 1,
            "regex": "",
            "skipUrlSync": false,
            "sort": 0,
            "tagValuesQuery": "",
            "tagsQuery": "",
            "type": "query",
            "useTags": false
          }
        ]
      },
      "time": {
        "from": "now-1h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "Model Monitoring - Performance",
      "uid": "9CazA-UGz",
      "version": 3,
      "weekStart": ""
    }
kind: ConfigMap
metadata:
  labels:
    grafana_dashboard: "1"
  name: model-monitoring-performance
{{- end -}}