{{- if eq .Values.storage.mode "azure-blob" }}
apiVersion: v1
kind: Secret
metadata:
  name: storage-credentials
  labels:
    {{- include "mlrun-ce.common.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.storage.azure.connectionString }}
  AZURE_STORAGE_CONNECTION_STRING: {{ . }}
  {{- end }}
  {{- with .Values.storage.azure.accountName }}
  AZURE_STORAGE_ACCOUNT_NAME: {{ . }}
  {{- end }}
  {{- with .Values.storage.azure.accountKey }}
  AZURE_STORAGE_ACCOUNT_KEY: {{ . }}
  {{- end }}
  {{- with .Values.storage.azure.sasToken }}
  AZURE_STORAGE_SAS_TOKEN: {{ . }}
  {{- end }}
  {{- with .Values.storage.azure.clientSecret }}
  AZURE_STORAGE_CLIENT_SECRET: {{ . }}
  {{- end }}
  {{- with .Values.storage.azure.tenantId }}
  AZURE_STORAGE_TENANT_ID: {{ . }}
  {{- end }}
{{- else if not .Values.global.infrastructure.aws.s3NonAnonymous }}
apiVersion: v1
kind: Secret
metadata:
  name: storage-credentials
  labels:
    {{- include "mlrun-ce.common.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ include "mlrun-ce.s3.accessKey" . }}
  AWS_SECRET_ACCESS_KEY: {{ include "mlrun-ce.s3.secretKey" . }}
  {{- if eq .Values.storage.mode "local" }}
  AWS_ENDPOINT_URL_S3: {{ include "mlrun-ce.s3.service.url" . }}
  {{- end }}
{{- end }}
