{{- if and (eq .Values.storage.mode "s3") (not .Values.storage.s3.bucket) }}
{{ fail "storage.mode is set to \"s3\" but storage.s3.bucket is not provided. Please set storage.s3.bucket." }}
{{- end }}
{{- if and (eq .Values.storage.mode "azure-blob") (not .Values.storage.azure.containerName) }}
{{ fail "storage.mode is set to \"azure-blob\" but storage.azure.containerName is not provided. Please set storage.azure.containerName." }}
{{- end }}