name: Release Charts

permissions:
  contents: read

on:
  push:
    branches:
      - development
      - "[0-9]+.[0-9]+.x"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 #v4.3.1

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Add Helm Repos
        run: |
          helm repo add stable https://charts.helm.sh/stable
          helm repo add nuclio https://nuclio.github.io/nuclio/charts
          helm repo add v3io-stable https://v3io.github.io/helm-charts/stable
          helm repo add minio https://charts.min.io/
          helm repo add spark-operator https://kubeflow.github.io/spark-operator
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Extract Chart Version from Chart.yaml
        id: extract_version
        run: |
          CHART_VERSION=$(grep '^version:' charts/mlrun-ce/Chart.yaml | awk '{print $2}')
          if [[ -z "$CHART_VERSION" ]]; then
            echo "Error: Failed to extract version from Chart.yaml" >&2
            exit 1
          fi
          echo "version=$CHART_VERSION" >> $GITHUB_OUTPUT

    outputs:
      version: ${{ steps.extract_version.outputs.version }}

  deploy_ce_onprem:
    needs: release
    uses: ./.github/workflows/deploy_ce_onprem_public.yaml
    with:
      version: ${{ needs.release.outputs.version }}
    secrets:
      GH_APP_ID: ${{ secrets.GH_APP_ID }}
      GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
      DEPLOYMENT_REPO: ${{ secrets.DEPLOYMENT_REPO }}
      SYSTEM_ID: ${{ secrets.SYSTEM_ID }}